name: aplicacao
description: "Software de Avaliação da Atenção."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3

  # PDF
  pdf: ^3.9.0
  printing: ^5.13.0

  # Outros
  cupertino_icons: ^1.0.8
  keyboard_actions: ^4.2.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/img5.png
    - assets/images/img6.png
    - assets/images/img7.png
    - assets/images/img8.png
    - assets/images/img9.png
    - assets/images/img10.png
    - assets/images/img11.png
    - assets/images/img12.png
    - assets/images/img13.png
    - assets/images/img14.png
    - assets/images/img15.png
    - assets/images/img16.png
    - assets/images/img17.png
    - assets/images/img18.png
    - assets/images/img19.png
    - assets/images/img20.png
    - assets/images/spacebar_normal.png
    - assets/images/spacebar_pressed.png
    - assets/images/arrow_right_normal.png
    - assets/images/arrow_right_pressed.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
